# Generated by Django 5.1.6 on 2025-03-25 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmnaminAuthentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
