# Generated by Django 5.1.7 on 2025-03-25 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmnaminAuthentication', '0002_authentication_delete_testmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authentication',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='authentication',
            name='username',
            field=models.CharField(max_length=150),
        ),
    ]
