# Generated by Django 5.1.7 on 2025-03-25 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmnaminAuthentication', '0003_alter_authentication_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authentication',
            name='password',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='authentication',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
