# Generated by Django 5.1.7 on 2025-03-25 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['id']},
        ),
    ]
